<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; line-height: 1.6; color: #333; }
        .container { width: 90%; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .header { background-color: #FF6600; color: white; padding: 10px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { padding: 20px 0; }
        .detail { margin-bottom: 15px; padding: 10px; background-color: #f9f9f9; border-left: 3px solid #FF6600; border-radius: 4px; }
        .detail strong { display: block; margin-bottom: 5px; color: #1a1a1a; font-weight: bold; }
        .message-box { padding: 15px; border: 1px dashed #ccc; background-color: #fff; border-radius: 4px; white-space: pre-wrap; }
        .footer { text-align: center; font-size: 0.8em; color: #999; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>New Service Request Received</h2>
        </div>
        
        <div class="content">
            <p>A new service request has been submitted through the Jordan's Mobile Fleet Service website contact form.</p>

            <div class="detail">
                <strong>Sender Name:</strong>
                {{ $name }}
            </div>

            <div class="detail">
                <strong>Sender Email:</strong>
                {{ $user_email }}
            </div>

            <p><strong>Service Request Details:</strong></p>
            <div class="message-box">
                {{ $user_message }}
            </div>

            <p style="margin-top: 25px;">You can reply directly to this email ({{ $user_email }}) to contact the customer.</p>
        </div>

        <div class="footer">
            This email was automatically generated by the contact form at jordansmobilefleetservice.com.
        </div>
    </div>
</body>
</html>